---
- name: Ensure backup directory exists
  ansible.builtin.file:
    path: "{{ backup_directory }}"
    mode: 0644
    state: directory

- name: Add DB password to Environment Variables
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^{{ database_password_variable }}='
    line: "{{ database_password_variable }}={{ database_password }}"


- name: Install MariaDB Client
  become: true
  ansible.builtin.apt:
    name: mariadb-client
    state: present

- name: Install backup script
  ansible.builtin.template:
    src: backup_mariadb.sh.j2
    dest: "{{ parent_directory }}/backup_mariadb_{{ database_name }}.sh"
    mode: 0644

- name: Run script daily
  ansible.builtin.cron:
    name: "Backup Database - {{ database_name }}"
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: "3"
    job: "{{ parent_directory }}/backup_mariadb_{{ database_name }}.sh"
    state: present

    